name: Labeler

on:
  push:
    branches: [master]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          skip-delete: true
          yaml-file: .github/labels.yml
